config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root 'fraternities#index', as: :authenticated_root
  end

  resources :fraternities do
    resources :memberships
    resources :transactions, only: %i[index show create]
    resources :batch_meetings, only: %i[new create]
    resources :meetings do
      resource :attendance_records, only: :create
    end
  end

  root 'pages#home'
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :fraternity

  has_many :transactions, dependent: :destroy

  enum role: { owner: 0, admin: 1, member: 2 }

  validates :role, presence: true

  delegate :email, :name, to: :user

  def to_s
    name || nickname || ''
  end

  def balance
    transactions.sum(:amount)
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    authorize @fraternity, :show?
    load_memberships
  end

  def new
    authorize @fraternity, :update?
    @membership_form = MembershipForm.new
  end

  def create
    authorize @fraternity, :update?
    @membership_form = MembershipForm.new(membership_params)

    if @membership_form.valid?
      CreateMembership.call(fraternity: @fraternity, **@membership_form.attributes)

      redirect_to fraternity_memberships_path(@fraternity), notice: notification_for(:invited, User)
    else
      render :new
    end
  end

  def edit
    load_membership
    authorize @membership
  end

  def update
    load_membership
    authorize @membership
    build_membership

    if @membership.save
      redirect_to fraternity_memberships_path(@fraternity), notice: notification_for(:updated, Membership)
    else
      render :edit
    end
  end

  def destroy
    load_membership
    authorize @membership

    options =
      if @membership.destroy
        { notice: notification_for(:destroyed, Membership) }
      else
        { flash: { alert: notification_for(:not_destroyed, Membership) } }
      end

    redirect_to fraternity_memberships_path(@membership.fraternity), options
  end

  private

  def membership_params
    params.fetch(:membership, {}).permit(:email, :nickname, :role)
  end

  def build_membership
    @membership ||= membership_scope.build
    @membership.attributes = membership_params
  end

  def load_membership
    @membership ||= membership_scope.find_by(id: params[:id])
  end

  def load_memberships
    @memberships ||= membership_scope.includes(:user)
  end

  def membership_scope
    @fraternity.memberships || Membership.all
  end
end

app/views/memberships/_membership.html.slim
.card.mb-3.elevate
  .card-body
    .row
      .col-md-6.d-flex.flex-column.justify-content-center.align-items-center
        .font-size-4.text-center.text-truncate class=class_string(['text-danger', 'text-success'] => membership.balance.negative?)
          = formatted_amount membership.balance

        - if policy(@fraternity).edit?
          .w-50.mb-3
            = form_for :transaction, url: fraternity_transactions_path(@fraternity) do |f|
              = f.hidden_field :membership_id, value: membership.id
              .row.justify-content-md-center
                .col-md-auto.col-md-5.col-sm-12.py-1.px-0
                  = f.number_field :amount, class: 'form-control number-field', min: -999999, max: 999999, step: 0.5, data: { transaction_field: '' }
                .col-md-7.col-sm-12.py-1.d-flex.justify-content-center
                  = f.submit t('actions.save'), class: 'btn btn-outline-secondary'

      .col-md-6.d-flex.flex-column.justify-content-center.align-items-center
        .text-center
          - if policy(@fraternity).edit?
            = link_to edit_fraternity_membership_path(@fraternity, membership) do
              h3.card-title.text-dark = membership
              small.badge.badge-secondary = membership.role
          - else
            h3.card-title = membership
            small.badge.badge-secondary = membership.role

app/views/memberships/edit.html.slim
.form-card.my-5.mx-auto.pb-5.px-4
  .my-2
    = link_to fraternity_memberships_path(@fraternity) do
      = icon('chevron-circle-left', t('general.back'))

  .card.card-narrow.py-5.px-4
    .card-body
      h4.mb-4.text-center.card-title = t('.title')

    = form_for @membership, url: fraternity_membership_path(@fraternity, @membership) do |f|
      = f.field_wrapper :nickname, class: 'form-group' do
        = f.label t('.nickname'), class: 'form-control-label'
        = f.text_field :nickname, class: 'form-control', placeholder: t('.nickname')

      = f.field_wrapper :role, class: 'form-group' do
        = f.label t('.role'), class: 'form-control-label'
        = f.select :role, Membership.roles.keys, {}, class: 'form-control'

      = f.submit t('actions.save'), class: 'btn btn-secondary'

app/views/memberships/index.html.slim
= content_for(:tab_navigation) do
  = render 'shared/tab_navigation'

.text-center
  = link_to t('.add'), new_fraternity_membership_path, class: 'px-5 my-5 btn btn-secondary'

.container
  = render(@memberships)

app/views/memberships/new.html.slim
.form-card.my-5.mx-auto.pb-5.px-4
  .my-2
    = link_to fraternity_memberships_path(@fraternity) do
      = icon('chevron-circle-left', t('general.back'))

  .card.card-narrow.py-5.px-4
    .card-body
      h4.mb-4.text-center.card-title = t('.title')

      = form_for @membership_form, as: :membership, url: fraternity_memberships_path(@fraternity) do |f|
        = @membership_form.errors.full_messages.join(', ')

        = f.field_wrapper :email, class: 'form-group mb-4' do
          .input-group
            span.input-group-addon
              = icon('envelope')
            = f.email_field :email, class: 'form-control', placeholder: t('.email')

        = f.field_wrapper :nickname, class: 'form-group mb-4' do
          .input-group
            span.input-group-addon
              = icon('user-circle')
            = f.text_field :nickname, class: 'form-control', placeholder: t('.nickname')

        .text-center
          = f.submit t('actions.save'), class: 'btn btn-secondary px-5'