config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root 'fraternities#index', as: :authenticated_root
  end

  resources :fraternities do
    resources :memberships
    resources :transactions, only: %i[index show create]
    resources :batch_meetings, only: %i[new create]
    resources :meetings do
      resource :attendance_records, only: :create
    end
  end

  root 'pages#home'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :fraternity

  has_many :organizer_assignations, dependent: :destroy
  has_many :organizers, through: :organizer_assignations, source: :organizer
  has_many :attendance_records, dependent: :destroy

  scope :upcoming, -> { where('date >= ?', Time.zone.today).order(:date) }
  scope :ordered, -> { order(date: :asc) }

  validates :date, presence: true

  def organizers_names
    organizers.map(&:name).join(' & ')
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    authorize @fraternity, :show?
    load_event_meetings
  end

  def show
    load_meeting
    authorize @meeting
  end

  def new
    build_meeting
    authorize @meeting
  end

  def create
    build_meeting
    authorize @meeting

    if @meeting.save
      redirect_to fraternity_meetings_path(@fraternity), notice: notification_for(:created, Meeting)
    else
      render :new
    end
  end

  def edit
    load_meeting
    authorize @meeting
  end

  def update
    load_meeting
    authorize @meeting
    build_meeting

    if @meeting.save
      redirect_to fraternity_meetings_path(@fraternity), notice: notification_for(:updated, Meeting)
    else
      render :new
    end
  end

  private

  def meetings_params
    params.fetch(:meeting, {}).permit(:date, organizer_ids: [])
  end

  def build_meeting
    @meeting ||= meetings_scope.build
    @meeting.attributes = meetings_params
  end

  def load_meeting
    @meeting ||= meetings_scope.find_by(id: params[:id])
  end

  def load_event_meetings
    @events = meetings.map do |meeting|
      {
        date: meeting.date.strftime('%Y/%m/%d'),
        title: meeting.organizers_names,
        link: fraternity_meeting_path(meeting.fraternity, meeting)
      }
    end
  end

  def meetings
    @meetings ||= meetings_scope.upcoming
  end

  def meetings_scope
    @fraternity.meetings || Meeting.all
  end
end

app/views/meetings/_form.html.slim
.form-card.my-5.mx-auto.pb-5.px-4
  .my-2
    = link_to fraternity_meetings_path(@fraternity) do
      = icon('chevron-circle-left', t('general.back'))

  .card.card-narrow.py-2.px-4
    .card-body
      h4.mb-4.text-center.card-tile = yield(:title)

      = form_for [@fraternity, @meeting] do |f|
        = f.field_wrapper :date, class: 'form-group d-flex justify-content-center' do
          div data-datepicker=true
            = f.hidden_field :date, class: 'form-control', id: 'date'

        = f.field_wrapper :organizer_ids, class: 'form-group btn-group d-block', data: { toggle: 'buttons'} do
          .text-center = t('.organizers')

          = f.collection_check_boxes :organizer_ids, @meeting.fraternity.memberships.all, :user_id, :to_s, {}, multiple: true do |ff|
            .btn.btn-outline-secondary.d-block.my-1.px-2.rounded class=class_string(active: @meeting.organizer_ids.include?(ff.object.user_id))
              = ff.label { ff.check_box }
              = ff.object.to_s

        .text-center
          = f.submit t('actions.save'), class: 'btn btn-secondary px-5'

app/views/meetings/edit.html.slim
- provide(:title) { t('.title') }

= render 'form'

app/views/meetings/index.html.slim
= content_for(:tab_navigation) do
  = render 'shared/tab_navigation'

.row.mb-4
  .col-md-6.col-sm-12.py-2.text-center
    = link_to t('.new_meeting'), new_fraternity_meeting_path(@fraternity), class: 'px-5 btn btn-secondary'
  .col-md-6.col-sm-12.py-2.text-center
    = link_to t('.random_generator'), new_fraternity_batch_meeting_path, class: 'px-5 btn btn-secondary'

.container.my-5.pb-5
  div#meetings-calendar data-meetings=@events.to_json

app/views/meetings/show.html.slim
.form-card.my-5.mx-auto.pb-5.px-4
  .my-2
    = link_to fraternity_meetings_path(@fraternity) do
      = icon('chevron-circle-left', t('general.back'))

  .card.card-narrow.py-5.px-4
    .card-body
      h2.card-title.mb-4
        = t('.title')
        =< I18n.localize(@meeting.date, format: :date_with_day_in_words)

      .mb-4
        h5 = t('.organizers')
        hr
        = @meeting.organizers_names

      - if @meeting.attendance_records.empty?
        h5 = t('.attendance')
        hr

        = form_for :attendance_record, url: fraternity_meeting_attendance_records_path(@fraternity, @meeting) do |f|
          .form-group.btn-group.d-block data-toggle='buttons'
            = collection_check_boxes :attendance_record, :absent_user_ids, @fraternity.memberships.all, :user_id, :to_s, {}, multiple: true do |ff|
              .btn.btn-light.attendace.d-flex.my-1.rounded
                = ff.label { ff.check_box }
                = ff.object.to_s
                .absence.badge.badge-danger.ml-auto = t('.absent')

          .text-center
            = f.submit t('actions.save'), class: 'btn btn-secondary px-5'