config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root 'fraternities#index', as: :authenticated_root
  end

  resources :fraternities do
    resources :memberships
    resources :transactions, only: %i[index show create]
    resources :batch_meetings, only: %i[new create]
    resources :meetings do
      resource :attendance_records, only: :create
    end
  end

  root 'pages#home'
end

app/views/shared/_empty.html.slim
.card.elevate
  .card-body
    h4.card-title.text-center
      = t('.title', subject: subject.model_name.human(count: 0))

app/views/shared/_footer.html.slim
.row
  .col-sm-4.text-center.text-sm-left
    = t('general.copyright', year: Date.today.year)

  .col-sm-8.text-center.text-sm-right
    = t('general.made_by_html')

app/views/shared/_fraternity_header.html.slim
.py-5.elevate
  h1.text-center = current_fraternity.name

app/views/shared/_tab_navigation.html.slim
ul.nav.nav-pills.nav-fill.my-4
  li.nav-item.border.border-secondary.rounded.mx-2
    = link_to fraternity_memberships_path(@fraternity), class: class_string('nav-link py-4', active: controller_name == 'memberships') do
      = t('.members')

  li.nav-item.border.border-secondary.rounded.mx-2
    = link_to fraternity_meetings_path(@fraternity), class: class_string('nav-link py-4', active: controller_name == 'meetings') do
      = t('.events')

app/views/shared/_user_header.html.slim
.user-header
  .container
    .d-flex.py-4
      .d-flex.align-items-top
        h1 = @fraternity&.name

      .w-100.d-flex.justify-content-end
        div
          h5.text-center = t('.upcoming_events')
          - if @upcoming = @fraternity&.next_meeting

            .d-flex.justify-content-center
              = link_to fraternity_meeting_path(@fraternity, @upcoming) do
                .card.calendar-card
                  .card-header.bg-primary.text-white
                    .text-center.font-weight-bold.mx-auto = I18n.localize(@upcoming.date, format: :month_abbreviated)

                  .card-body
                    .text-center = @upcoming.date.strftime('%d')