config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root 'fraternities#index', as: :authenticated_root
  end

  resources :fraternities do
    resources :memberships
    resources :transactions, only: %i[index show create]
    resources :batch_meetings, only: %i[new create]
    resources :meetings do
      resource :attendance_records, only: :create
    end
  end

  root 'pages#home'
end

app/models/fraternity.rb
class Fraternity < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :meetings, dependent: :destroy
  has_many :transactions, through: :memberships, dependent: :destroy

  validates :name, presence: true
  validates :absent_penalty, numericality: { greater_than_or_equal_to: -9999, less_than_or_equal_to: 0 }

  def owner
    memberships.find_by(role: :owner)
  end

  def next_meeting
    meetings&.upcoming&.first
  end

  def balance
    transactions.sum(:amount)
  end
end

app/controllers/fraternities_controller.rb
class FraternitiesController < ApplicationController
  def index
    authorize Fraternity
    load_fraternities
  end

  def show
    authorize @fraternity
  end

  def new
    @fraternity = fraternity_scope.build
    authorize @fraternity
  end

  def edit
    authorize @fraternity
    build_fraternity
  end

  def create
    authorize Fraternity
    CreateFraternity.call(name: fraternity_params[:name], user: current_user) do |result|
      result.success { redirect_to fraternities_path }
      result.failure do |fraternity|
        @fraternity = fraternity
        render :new
      end
    end
  end

  def update
    authorize @fraternity
    build_fraternity

    if @fraternity.save
      redirect_to fraternity_memberships_path(@fraternity)
    else
      render :edit
    end
  end

  def destroy
    authorize @fraternity

    @fraternity.destroy

    redirect_to fraternities_path
  end

  private

  def load_fraternities
    @fraternities ||= fraternity_scope
  end

  def build_fraternity
    @fraternity ||= fraternity_scope.build
    @fraternity.attributes = fraternity_params
  end

  def fraternity_params
    params.fetch(:fraternity, {}).permit(:name, :absent_penalty)
  end
end

app/views/fraternities/_form.html.slim
.card.card-narrow.py-5.px-4
  .card-body
    h4.mb-4.text-center.card-title = yield(:title)

    = form_for(@fraternity) do |f|
      = f.field_wrapper :name, class: 'form-group' do
        = f.label t('.name')
        = f.text_field :name, class: 'form-control'

      = f.field_wrapper :absent_penalty, class: 'form-group' do
        = f.label t('.absent_penalty')
        = f.number_field :absent_penalty, class: 'form-control', min: -999999, max: 0, step: 1

      .text-center
        = f.submit t('actions.save'), class: 'btn btn-secondary px-5'

app/views/fraternities/_fraternity.html.slim
.card.mb-3
  .card-body
    .row
      .col-md-6.d-flex.flex-column.justify-content-center.align-items-center
        .font-size-4 class=class_string(['text-danger', 'text-success'] => fraternity.balance.negative?)
          = formatted_amount fraternity.balance

      .col-md-6.d-flex.flex-column.justify-content-center.align-items-center
        .text-center.h1.card-title = link_to fraternity.name, fraternity_memberships_path(fraternity)

  .card-footer
    = link_to fraternity_memberships_path(fraternity) do
      => fraternity.memberships.count
      = plural_name_for(User)

    = link_to fraternity_meetings_path(fraternity), class: 'float-right' do
      => fraternity.meetings.count
      = plural_name_for(Meeting)

app/views/fraternities/_header.html.slim
.card.card-narrow.user-header
  .container
    .row
      .col-sm-4
        h2 = t('general.title')

      .col-sm-4
        = t('shared.user_header.welcome', subject: current_user.name)
        = link_to t('actions.sign_out'), destroy_user_session_path, method: 'delete', class: 'ml-2'

      .col-sm-4.text-right
        = icon('cog')

  .text-center.position-bottom
    h2 = t('fraternities.my_fraternities')

app/views/fraternities/edit.html.slim
- content_for(:title) { t('.title') }

.form-card.my-5.mx-auto.pb-5.px-4
  .my-2
    = link_to fraternity_memberships_path(@fraternity) do
      = icon('chevron-circle-left', t('general.back'))

    = render 'form'

app/views/fraternities/index.html.slim
= content_for(:title) { t('.title') }

h4.mb-3
  = t('.title')

.text-center.mb-4
  = link_to new_fraternity_path, class: 'btn btn-primary' do
    = t('.new', subject: Fraternity.model_name.human)

= render(@fraternities)

app/views/fraternities/new.html.slim
- content_for(:title) { t('.title') }

.form-card.my-5.mx-auto.pb-5.px-4
  .my-2
    = link_to fraternities_path do
      = icon('chevron-circle-left', t('general.back'))

  = render 'form'

app/views/fraternities/show.html.slim
= render 'shared/user_header'